import Head from 'next/head'
import Link from 'next/link';
import { useEffect, useState } from 'react'
import styles from '../styles/Home.module.css'

interface Pokemon {
  id: number;
  name: string;
  image: string;
}

export default function Home() {

  const [pokemon, setPokemon] = useState<Pokemon[]>([])

  useEffect(() => {
    async function getPokemon() {
      const res = await fetch("https://raw.githubusercontent.com/jherr/pokemon/main/index.json")
      setPokemon(await res.json())
    }
    getPokemon()
  }, [])

  console.log(pokemon);
  

  return (
    <>
      <Head>
        <title>Pokedex</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.grid}>
          {pokemon.map((pokemon: Pokemon) => (
            <div className={styles.card} key={pokemon.id}>
              <Link href={`/pokemon/${pokemon.id}`}>
                <img src={`https://jherr-pokemon.s3.us-west-1.amazonaws.com/${pokemon.image}`} alt={pokemon.name} />
                <p>{pokemon.name}</p>
              </Link>
            </div>
          ))}
        </div>
      </main>
    </>
  )
}
